import {nativeFirebaseConfig} from '../mobile/scripts/firebase-config.mjs';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const root=new URL('../',import.meta.url);
let source=await readFile(new URL('app/native.js',root),'utf8');
const calls=[],files=new Map();let requestHandler=async()=>({status:200,data:{success:true}});
globalThis.Capacitor={isNativePlatform:()=>true,getPlatform:()=> 'ios'};
globalThis.__nativeTestPlugins=[{CapacitorHttp:{request:async o=>{calls.push(o);return requestHandler(o);}}},{FirebaseAuthentication:{signInWithApple:async()=>({credential:{idToken:'token',nonce:'nonce'}}),signOut:async()=>{}}},{Directory:{Cache:'CACHE'},Filesystem:{writeFile:async o=>files.set(o.path,Buffer.from(o.data,'base64')),appendFile:async o=>files.set(o.path,Buffer.concat([files.get(o.path),Buffer.from(o.data,'base64')])),getUri:async o=>({uri:o.path}),deleteFile:async o=>files.delete(o.path)}},{Share:{share:async o=>assert.deepEqual(files.get(o.files[0]),fixture)}},{},{}];
source=source.replace(/const dependencies=\(\)=>Promise\.all\(\[.*?\]\);/, 'const dependencies=()=>Promise.resolve(globalThis.__nativeTestPlugins);');
const api=await import(`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`);
const fixture=Buffer.from(Array.from({length:1800000},(_,i)=>i%256));
assert.deepEqual(await api.signInNative('apple.com'),{idToken:'token',accessToken:undefined,rawNonce:'nonce',authorizationCode:undefined});
const response=await api.nativeApiRequest('/api/videos/chunk',{method:'PUT',raw:new Blob([fixture]),csrf:'csrf'});
assert.equal(response.ok,true);assert.deepEqual(await response.json(),{success:true});
assert.equal(calls[0].url,'https://60base.ai/api/videos/chunk');assert.equal(calls[0].dataType,'file');assert.deepEqual(Buffer.from(calls[0].data,'base64'),fixture);assert.equal(calls[0].headers.Origin,'https://60base.ai');assert.equal(calls[0].headers['X-CSRF-Token'],'csrf');assert.equal(calls[0].disableRedirects,true);
await assert.rejects(api.nativeApiRequest('/api/upload',{raw:new Blob([new Uint8Array(2*1024*1024+1)])}));
for(const path of ['https://evil.test/api/x','https://60base.kr/api/x','https://60base.ai/api/x','//60base.kr/api/x','//evil.test/api/x','/api/../../secret'])await assert.rejects(api.nativeApiRequest(path));
const controller=new AbortController();controller.abort();const count=calls.length;await assert.rejects(api.nativeApiRequest('/api/me',{signal:controller.signal}),{name:'AbortError'});assert.equal(calls.length,count);
const during=new AbortController();requestHandler=async()=>{during.abort();return {status:200,data:{}};};await assert.rejects(api.nativeApiRequest('/api/me',{signal:during.signal}),{name:'AbortError'});
assert.equal(await api.shareNativeBlob(new Blob([fixture]),'video.mp4'),true);assert.equal(files.size,0);
globalThis.__nativeTestPlugins[3].Share.share=async()=>{throw new Error('cancelled');};await assert.rejects(api.shareNativeBlob(new Blob([fixture]),'video.mp4'));assert.equal(files.size,0);
const android=await readFile(new URL('mobile/node_modules/@capacitor/android/capacitor/src/main/java/com/getcapacitor/plugin/util/CapacitorHttpUrlConnection.java',root),'utf8');
const ios=await readFile(new URL('mobile/node_modules/@capacitor/ios/Capacitor/Capacitor/Plugins/CapacitorUrlRequest.swift',root),'utf8');
assert.match(android,/bodyType\.equals\("file"\)[\s\S]*?Base64\.getDecoder\(\)\.decode\(body\.toString\(\)\)/);assert.match(ios,/dataType == "file"[\s\S]*?Data\(base64Encoded: stringData\)/);
Capacitor.isNativePlatform=()=>false;assert.equal(await api.signInNative('apple.com'),null);assert.equal(await api.shareNativeBlob(new Blob(),'x'),false);
console.log('Native adapter: auth credential, bounded raw bytes, destination, CSRF, cancellation fencing, share cleanup and native decoder source checks passed. Actual device bridge remains release QA.');

const publicFixture=Object.freeze({apiKey:'unit-test-only',authDomain:'fixture.invalid',projectId:'fixture',appId:'fixture',appleEnabled:true});
assert.equal(nativeFirebaseConfig(publicFixture,undefined).appleEnabled,false);
assert.equal(nativeFirebaseConfig(publicFixture,'true').appleEnabled,false);
assert.equal(nativeFirebaseConfig(publicFixture,'1').appleEnabled,true);
assert.equal(publicFixture.appleEnabled,true);
assert.equal(nativeFirebaseConfig(null,undefined),null);
assert.throws(()=>nativeFirebaseConfig(null,'1'));
assert.throws(()=>nativeFirebaseConfig({},'1'));
console.log('Native Apple config gate passed: explicit flag only, complete public config required, source unchanged.');

Capacitor.isNativePlatform=()=>true;
const filesystem=globalThis.__nativeTestPlugins[2].Filesystem;
const deleteNormally=filesystem.deleteFile;
globalThis.__nativeTestPlugins[3].Share.share=async()=>{};
filesystem.deleteFile=async()=>{throw Object.assign(new Error('disk unavailable'),{code:'OS-PLUG-FILE-0013'});};
await assert.rejects(api.shareNativeBlob(new Blob([fixture]),'video.mp4'),error=>error.message.includes('임시 영상 정리')&&error.cause.code==='OS-PLUG-FILE-0013');
assert.equal(files.size,1,'failed cleanup must not report successful sharing');
filesystem.deleteFile=async options=>{await deleteNormally(options);throw Object.assign(new Error('already removed'),{code:'OS-PLUG-FILE-0008'});};
assert.equal(await api.shareNativeBlob(new Blob([fixture]),'video.mp4'),true,'documented not-found is idempotent');
const listeners=new Map(),nativeListeners=[];
globalThis.document={documentElement:{dataset:{}},addEventListener:(type,listener)=>{assert.equal(listeners.has(type),false,'retry must not duplicate navigation listeners');listeners.set(type,listener);},dispatchEvent:()=>{},querySelector:()=>null};
globalThis.location={href:'https://localhost/app/',origin:'https://localhost',hash:'#home'};
const opened=[];
globalThis.__nativeTestPlugins[4].App={addListener:async type=>nativeListeners.push(type),minimizeApp:()=>{}};
globalThis.__nativeTestPlugins[5].Browser={open:async options=>opened.push(options.url)};
filesystem.readdir=async()=>{throw Object.assign(new Error('cannot read cache'),{code:'OS-PLUG-FILE-0013'});};
await assert.rejects(api.initializeNative(),/임시 영상 정리/);
assert.equal(document.documentElement.dataset.nativePlatform,'ios','Native layout keeps its platform scope even if private-cache cleanup requires retry');
let prevented=false;
listeners.get('click')({target:{closest:()=>({href:'https://example.com/'})},preventDefault:()=>{prevented=true;}});
assert.equal(prevented,true);assert.deepEqual(opened,['https://example.com/'],'navigation remains protected despite cleanup failure');
for(const path of ['/?lang=ko#contact','/admin/?view=videos#pending']){
 listeners.get('click')({target:{closest:()=>({href:'https://localhost'+path})},preventDefault:()=>{}});
 assert.equal(opened.at(-1),'https://60base.ai'+path);
}
filesystem.readdir=async()=>({files:[{name:'another-app-file'},{name:'60base-share-../outside'},{name:'60base-share-recovery.mp4'}]});
const deleted=[];
filesystem.deleteFile=async options=>{deleted.push(options.path);throw Object.assign(new Error('cannot delete cache'),{code:'OS-PLUG-FILE-0013'});};
await assert.rejects(api.initializeNative(),/임시 영상 정리/);
assert.deepEqual(deleted,['60base-share-recovery.mp4'],'never delete a foreign or nested path');
filesystem.deleteFile=async options=>{deleted.push(options.path);};
await api.initializeNative();
assert.deepEqual(deleted,['60base-share-recovery.mp4','60base-share-recovery.mp4'],'initialization retries failed cleanup');
assert.deepEqual(nativeListeners,['backButton','appStateChange']);
await api.initializeNative();assert.equal(deleted.length,2,'successful initialization is idempotent');
// A native missing-cache error is the only read failure tolerated.
const missingApi=await import(`data:text/javascript;base64,${Buffer.from(source+'\n// missing cache scenario').toString('base64')}`);
listeners.clear();filesystem.readdir=async()=>{throw Object.assign(new Error('cache absent'),{code:'OS-PLUG-FILE-0008'});};
await missingApi.initializeNative();
let installSource=await readFile(new URL('app/install.js',root),'utf8');
installSource=installSource.replace("import { isNativeApp, initializeNative } from './native.js';","const isNativeApp=()=>true;const initializeNative=()=>globalThis.__initializeForInstall();").replace("import { dialog } from '../studio/online-api.js';","const dialog=()=>{};");
const install=await import(`data:text/javascript;base64,${Buffer.from(installSource).toString('base64')}`);
const visible=[];globalThis.__initializeForInstall=async()=>{throw new Error('임시 영상 정리 재시도 필요');};
install.initializeInstall({onMessage:message=>visible.push(message)});await new Promise(resolve=>setImmediate(resolve));
assert.deepEqual(visible,['임시 영상 정리 재시도 필요']);assert.equal(install.getInstallState().error,visible[0]);
globalThis.__initializeForInstall=async()=>{};install.initializeInstall();await new Promise(resolve=>setImmediate(resolve));assert.equal(install.getInstallState().error,'');
console.log('Native cleanup failures: share rejects, cache read/delete errors visible, initialization retries without duplicate listeners, navigation protected, foreign files preserved.');
