import assert from 'node:assert/strict';
import {mkdtemp,mkdir,rm,writeFile} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE||path.resolve(os.homedir(),'.claude/skills/gstack/node_modules/playwright/index.mjs')));
import {createService} from '../server/app.mjs';
import {hashPassword} from '../server/security.mjs';
const out=path.resolve(process.env.OPERATIONS_REVIEW_DIR||'../.omx/reviews/dongjakso-operations-20260914/browser');await mkdir(out,{recursive:true});
const directory=await mkdtemp(path.join(os.tmpdir(),'dongjakso-browser-')),base='http://localhost:4392',service=createService({directory,origin:base});
await new Promise(r=>service.server.listen(4392,'127.0.0.1',r));
const pw='QA-only-password-2026!',at=service.store.now();service.store.run("INSERT INTO users(id,email,password,name,role,createdAt,updatedAt) VALUES(?,?,?,?,?,?,?)",'qa-admin','qa-admin@example.test',await hashPassword(pw),'테스트 운영자','admin',at,at);
const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),adminContext=await browser.newContext({viewport:{width:1440,height:1000}}),admin=await adminContext.newPage();const errors=[],checks=[];for(const p of [page,admin])p.on('pageerror',e=>errors.push(e.message));
async function api(p,route,body,method='POST'){return p.evaluate(async({route,body,method})=>{const session=await(await fetch('/api/session')).json();const r=await fetch('/api'+route,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':session.csrf},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(JSON.stringify(data));return data;},{route,body,method});}
async function ready(p){await p.waitForLoadState('networkidle');await p.evaluate(()=>document.fonts.ready);await p.waitForTimeout(100);}
async function openAuthDialog(p){await p.locator('[data-online-account]').first().click();if(await p.locator('[data-account-action="login"]').count())await p.locator('[data-account-action="login"]').click();await p.locator('.online-dialog').waitFor();}
async function screenshot(p,name){await ready(p);await p.screenshot({path:path.join(out,name+'.png'),fullPage:true});}
try{
 await page.goto(base+'/studio/#home');await ready(page);await page.evaluate(async()=>{const online=await import('/studio/online-api.js');await online.sessionReady;online.showAccount();});await page.locator('[data-auth="register"]').click();const form=page.locator('.online-dialog form');await form.locator('[name="name"]').fill('검증 참여자');await form.locator('[name="email"]').fill('member@example.test');await form.locator('[name="password"]').fill(pw);for(const field of ['adult','terms','privacy'])await form.locator(`[name="${field}"]`).check();await form.locator('[type="submit"]').click();await page.locator('.online-dialog').waitFor({state:'detached'});await page.reload();await ready(page);assert.match(await page.locator('[data-online-account]').first().innerText(),/검증 참여자/);assert.equal(await page.locator('#admin-main,#sidebar-name').count(),0,'participant shell does not expose admin/sidebar identity slots');checks.push('member registration and account identity after reload');
 await page.locator('[data-online-submit]').click();await page.locator('.online-dialog [name="title"]').fill('검수 테스트 — 빨래 개기');await page.locator('.online-dialog [name="taskId"]').selectOption('folding-clothes');await page.locator('.online-dialog [name="file"]').setInputFiles(path.resolve('assets/videos/collection/folding-clothes.mp4'));for(const field of ['filming','privacy','usage','training','recordedInKorea'])await page.locator(`.online-dialog [name="${field}"]`).check();await page.locator('.online-dialog [type="submit"]').click();await page.locator('[data-submission-receipt]').waitFor({timeout:40000});await page.locator('[data-go-history]').click();await page.waitForURL('**/#reviews');await page.getByText('접수 완료',{exact:true}).last().waitFor();await screenshot(page,'participant-submitted-desktop');checks.push('actual file selected, consent, chunk upload and submitted video displayed');
 await admin.goto(base+'/admin/');await ready(admin);await admin.locator('[data-access]').click();await admin.locator('.online-dialog [name="email"]').fill('qa-admin@example.test');await admin.locator('.online-dialog [name="password"]').fill(pw);await admin.locator('.online-dialog [type="submit"]').click();await admin.locator('.online-dialog').waitFor({state:'detached'});await admin.locator('.online-kpi').first().waitFor();
 await admin.goto(base+'/admin/#videos');await ready(admin);const openSubmittedReview=async()=>{await admin.goto(base+'/admin/#videos');await ready(admin);await admin.locator('[data-admin-action="video"]').first().click();await admin.locator('[data-review]').waitFor();};await admin.locator('[data-admin-action="video"]').first().click();await admin.locator('[data-review]').waitFor();await admin.locator('[data-annotation] [name="label"]').fill('옷 접기');await admin.locator('[data-annotation] [type="submit"]').click();await admin.getByText('구간 라벨을 저장했습니다.',{exact:true}).waitFor();await admin.locator('video').evaluate(async v=>{await v.play();v.pause();});await screenshot(admin,'admin-review-desktop');await admin.locator('.admin-review-steps li[aria-current="step"]').filter({hasText:/AI 심사/}).waitFor();await admin.locator('[data-review] [value="approved"]').click();await admin.locator('.online-dialog').waitFor({state:'detached'});await openSubmittedReview();await admin.locator('.admin-review-steps li[aria-current="step"]').filter({hasText:/수작업 심사/}).waitFor();for(const field of ['framing','hands','privacy','completion'])await admin.locator(`[data-review] [name="${field}"]`).check();await admin.locator('[data-review] [value="approved"]').click();await admin.locator('.online-dialog').waitFor({state:'detached'});await openSubmittedReview();await admin.locator('.admin-review-steps li[aria-current="step"]').filter({hasText:/클라이언트 확인/}).waitFor();await admin.locator('[data-review] [value="approved"]').click();await admin.locator('.online-dialog').waitFor({state:'detached'});await page.reload();await ready(page);await page.getByText('3,000P',{exact:true}).first().waitFor();checks.push('administrator private playback, timed annotation, staged checklist approval and member reward');
 await page.goto(base+'/studio/#wallet');await ready(page);await page.getByRole('heading',{name:'국내 은행 연동 예정'}).waitFor();const blockedCalls=[];page.on('request',r=>{if(r.method()!=='GET'&&/\/api\/(payouts|orders|account)/.test(r.url()))blockedCalls.push(r.url());});for(const selector of ['[name="bank"]','[name="holder"]','[name="number"]','.online-bank-planned button'])assert.ok(await page.locator(selector).evaluateAll(nodes=>nodes.length>0&&nodes.every(n=>n.disabled)));await page.locator('.online-bank-planned button').evaluateAll(nodes=>nodes.forEach(n=>n.click()));assert.equal(await page.locator('[data-points-balance]').innerText(),'3,000P');assert.equal(await page.locator('[data-pending-points]').innerText(),'0P');await screenshot(page,'participant-wallet-desktop');assert.deepEqual(blockedCalls,[]);checks.push('approved points balance and disabled domestic bank/withdrawal UI with no requests');
 await admin.goto(base+'/admin/#payouts');await ready(admin);await admin.getByRole('heading',{name:'국내 은행 연동 예정'}).waitFor();assert.equal(await admin.locator('[data-admin-action="payout"]').count(),0);
 await api(admin,'/admin/products',{title:'검증용 헤드 마운트',description:'화면 검증용 상품입니다.',price:1000,stock:3,published:true});await api(admin,'/admin/announcements',{title:'촬영 전 확인사항',body:'가로 촬영과 손의 가시성을 확인해주세요.',published:true});
 await page.goto(base+'/studio/#shop');await ready(page);assert.ok(await page.locator('[data-order]').isDisabled());await page.getByText('촬영 전 확인사항',{exact:true}).waitFor();checks.push('read-only product preview and published notice');
 await page.goto(base+'/studio/#support');await ready(page);await page.locator('[data-new-ticket]').click();await page.locator('.online-dialog [name="subject"]').fill('촬영 기준 문의');await page.locator('.online-dialog [name="message"]').fill('손의 가시성 기준을 확인하고 싶습니다.');await page.locator('.online-dialog [type="submit"]').click();await page.locator('.online-dialog').waitFor({state:'detached'});await admin.goto(base+'/admin/#tickets');await ready(admin);await admin.locator('[data-admin-action="ticket"]').click();await admin.locator('.online-dialog [name="response"]').fill('촬영 교육의 구도 예시를 확인해주세요.');await admin.locator('.online-dialog [type="submit"]').click();await admin.locator('.online-dialog').waitFor({state:'detached'});await page.reload();await ready(page);await page.getByText('촬영 교육의 구도 예시를 확인해주세요.',{exact:false}).waitFor();checks.push('participant support and administrator reply');
 for(const width of [320,390,768,1440]){
  await page.setViewportSize({width,height:960});await admin.setViewportSize({width,height:960});
  for(const route of ['home','missions','guide','library','profile','reviews','wallet','shop','support']){await page.goto(base+'/studio/#'+route);await ready(page);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false,`Studio ${route} ${width} overflow`);assert.equal(await page.locator('.operator-demo-entry:visible').count(),0);assert.equal(await page.locator('.service-demo-note:visible').count(),0);if(width===390||width===1440)await screenshot(page,`participant-${route}-${width}`);}
  for(const route of ['overview','members','videos','tasks','data','finance','payouts','commerce','tickets','notices','audit','settings']){await admin.goto(base+'/admin/#'+route);await ready(admin);await admin.locator('[data-refresh]').waitFor();assert.equal(await admin.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`Admin ${route} ${width} overflow`);if(width===390||width===1440)await screenshot(admin,`admin-${route}-${width}`);}
  checks.push(`Studio 9 + admin 12 pages: ${width}px`);
 }
 // MediaRecorder WebM often has no container duration; validate actual packet timing.
 await page.goto(base+'/studio/#reviews');await ready(page);
 const webm=Buffer.from(await page.evaluate(async()=>{const canvas=document.createElement('canvas');canvas.width=320;canvas.height=180;const ctx=canvas.getContext('2d'),stream=canvas.captureStream(15),rec=new MediaRecorder(stream,{mimeType:'video/webm'}),chunks=[];return new Promise(resolve=>{rec.ondataavailable=e=>chunks.push(e.data);rec.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());resolve([...new Uint8Array(await new Blob(chunks).arrayBuffer())]);};let n=0;const draw=setInterval(()=>{ctx.fillStyle=n++%2?'#245bff':'#ffffff';ctx.fillRect(0,0,320,180);},60);rec.start();setTimeout(()=>{clearInterval(draw);rec.stop();},1200);});}));
 await page.locator('[data-upload]').click();await page.locator('.online-dialog [name="title"]').fill('브라우저 촬영 영상');await page.locator('.online-dialog [name="file"]').setInputFiles({name:'browser.webm',mimeType:'video/webm',buffer:webm});for(const field of ['filming','privacy','usage','training','recordedInKorea'])await page.locator(`.online-dialog [name="${field}"]`).check();await page.locator('.online-dialog [type="submit"]').click();await page.locator('[data-submission-receipt]').waitFor({timeout:30000});await page.locator('[data-go-history]').click();await page.getByRole('heading',{name:'브라우저 촬영 영상',exact:true}).waitFor();assert.ok(service.store.one("SELECT duration FROM videos WHERE title='브라우저 촬영 영상'").duration>0);checks.push('real MediaRecorder WebM without declared duration is validated and submitted');
 await page.setViewportSize({width:390,height:900});const accountTrigger=page.locator('[data-online-account]').first();await accountTrigger.click();await page.locator('#studio-account-menu').waitFor();await page.keyboard.press('Escape');await page.locator('#studio-account-menu').waitFor({state:'hidden'});assert.equal(await accountTrigger.evaluate(el=>document.activeElement===el),true);checks.push('account menu Escape and focus restoration');
 // A normal member must not see administrator data even by opening its URL.
 const memberAdmin=await context.newPage();await memberAdmin.goto(base+'/admin/');await ready(memberAdmin);await memberAdmin.getByText('관리자 계정으로 로그인해주세요.',{exact:true}).waitFor();assert.equal(await memberAdmin.locator('.online-kpi').count(),0);await memberAdmin.close();
 assert.deepEqual(errors,[]);await writeFile(path.join(out,'report.json'),JSON.stringify({status:'passed',checks,errors},null,2));console.log(JSON.stringify({status:'passed',checks},null,2));
}catch(error){await screenshot(page,'failure-participant').catch(()=>{});await screenshot(admin,'failure-admin').catch(()=>{});console.error('Browser errors:',errors);throw error;}finally{await browser.close();await service.close();await rm(directory,{recursive:true,force:true});}
