import { missions, getMission, formatDuration, formatBytes, statusLabel } from '../shared/data.js';
import { getClips, subscribe, getProfile, saveProfile, addExamples } from '../shared/store.js';
import { openCapture, openClip, openGuide } from '../shared/capture.js';
import { icon, escapeHTML as esc } from '../shared/ui.js';

const titles={home:'홈',missions:'미션 둘러보기',library:'내 기록',guide:'촬영 가이드',profile:'내 프로필'};
const state={route:'home',clips:[],profile:{name:'참여자',goal:3},loading:true,error:'',category:'전체',query:'',status:'all',sort:'newest',profileDraft:null};
const main=document.querySelector('#workspace');
const icons=()=>document.querySelectorAll('[data-icon]').forEach(el=>{el.innerHTML=icon(el.dataset.icon,20);});
const date=value=>new Intl.DateTimeFormat('ko-KR',{month:'2-digit',day:'2-digit'}).format(new Date(value));
function artwork(mission){
  const illustrations={
    table:'<ellipse cx="180" cy="91" rx="76" ry="17" fill="#bdce8c"/><ellipse cx="154" cy="65" rx="53" ry="38" fill="#fffef4"/><ellipse cx="154" cy="65" rx="33" ry="23" fill="none" stroke="#d2ddb7" stroke-width="2"/><rect x="224" y="28" width="29" height="47" rx="5" fill="#63794c"/><path d="M253 37c23-5 21 25 0 21" stroke="#63794c" stroke-width="6" fill="none"/><path d="M76 29v63m-9-63v18q9 13 18 0V29m-9 28v35" stroke="#5b7250" stroke-width="4" stroke-linecap="round"/>',
    laundry:'<rect x="91" y="70" width="145" height="25" rx="10" fill="#5a79c7"/><rect x="102" y="48" width="129" height="29" rx="9" fill="#99b0eb"/><rect x="113" y="25" width="109" height="29" rx="9" fill="#e5edff"/><path d="M117 40h94M110 65h112M100 86h126" stroke="#fff" opacity=".45" stroke-width="2"/>',
    shelf:'<path d="M57 91h229" stroke="#a77057" stroke-width="8"/><rect x="85" y="27" width="24" height="60" rx="3" fill="#d39370"/><rect x="112" y="18" width="29" height="69" rx="3" fill="#f8f3e9"/><rect x="145" y="37" width="18" height="50" rx="3" fill="#657c65"/><path d="m173 28 22-5 15 62-22 5z" fill="#e4b778"/><path d="M232 60h35v25h-35z" fill="#3d5549"/><path d="M248 60V31m0 13q-26-21-20-2 7 13 20 2m0-6q26-21 20-2-7 13-20 2" stroke="#3d5549" fill="none" stroke-width="3"/>',
    coffee:'<ellipse cx="169" cy="96" rx="60" ry="12" fill="#bfb7d4"/><path d="M119 36h89l-10 55h-69z" fill="#f9f6ff"/><path d="M208 45q40-5 28 24-12 12-33 6" stroke="#f9f6ff" stroke-width="10" fill="none"/><ellipse cx="163" cy="36" rx="44" ry="9" fill="#9c7d61"/><path d="M159 10q-8 10 0 17M180 6q-8 10 0 17" fill="none" stroke="#c0b4d6" stroke-width="3"/>',
    bag:'<rect x="109" y="35" width="110" height="68" rx="18" fill="#b49d62"/><path d="M141 37v-9a23 23 0 0 1 46 0v9" fill="none" stroke="#6a6844" stroke-width="6"/><rect x="125" y="60" width="78" height="27" rx="7" fill="#e5d9b3"/><path d="M143 73h42" stroke="#8f8354" stroke-width="2"/>',
    recycle:'<path d="m95 41 8 59h51l8-59" fill="#83b5a3"/><path d="m182 41 8 59h51l8-59" fill="#b8cfae"/><path d="M90 36h76m11 0h76" stroke="#477568" stroke-width="6" stroke-linecap="round"/><path d="m115 71 10-16 10 16h-20m82 0 10-16 10 16h-20" stroke="#f2fff5" fill="none" stroke-width="3"/>',
  };
  return `<svg viewBox="0 0 340 125" aria-hidden="true"><circle cx="295" cy="14" r="58" fill="currentColor" opacity=".04"/>${illustrations[mission.id]||illustrations.table}<path d="M24 21h9m-4-4v8M307 101h9m-4-4v8" stroke="currentColor" opacity=".3" stroke-width="1.5"/></svg>`;
}
function missionCard(mission){return `<article class="mission-tile"><button class="mission-art ${mission.color}" data-action="guide" data-id="${mission.id}" aria-label="${esc(mission.title)} 가이드">${artwork(mission)}<span class="art-label">${mission.category}</span></button><div class="mission-info"><div class="mission-meta"><span>${icon('clock',13)} 약 ${mission.duration}분</span><span>${mission.level}</span></div><h3><button data-action="guide" data-id="${mission.id}">${mission.title}</button></h3><p>${mission.description}</p><div class="mission-foot"><span>일상 동작 · 예시 미션</span><button class="icon-button" data-action="camera" data-id="${mission.id}" aria-label="${mission.title} 촬영">${icon('arrow',18)}</button></div></div></article>`;}
function clipRows(clips){return `<div class="record-table"><div class="record-head"><span>기록 이름</span><span>상태</span><span>길이</span><span>저장일</span><span></span></div>${clips.map(clip=>`<button class="record-row" data-action="clip" data-id="${esc(clip.id)}"><span class="record-name"><span class="record-thumb ${getMission(clip.missionId).color}">${icon('play',19)}</span><span><b>${esc(clip.title)}</b><small>${esc(clip.category)} · ${clip.example?'예시 기록':clip.source==='camera'?'카메라 촬영':'가져온 영상'}</small></span></span><span><span class="badge ${clip.status}">${statusLabel(clip.status)}</span></span><span class="record-length">${formatDuration(clip.duration)}</span><span class="record-date">${date(clip.createdAt)}</span><span>${icon('chevron',17)}</span></button>`).join('')}</div>`;}
function empty(){return `<div class="empty-state"><div class="empty-illustration">${icon('video',32)}<span>+</span></div><h3>첫 번째 기록을 기다리고 있어요</h3><p>익숙한 일상을 촬영하거나, 가지고 있는 영상을 가져와보세요.</p><div class="empty-actions"><button class="button primary" data-action="camera">${icon('camera',18)} 첫 기록 만들기</button><button class="button" data-action="upload">영상 가져오기</button></div></div>`;}
function pageHeading(eyebrow,title,description,action=''){return `<div class="page-heading"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="page-description">${description}</p></div>${action}</div>`;}
function home(){
  const real=state.clips.filter(c=>!c.example),seconds=real.reduce((sum,c)=>sum+c.duration,0),ready=real.filter(c=>c.status==='ready').length;
  const goal=state.profile.goal; const progress=Math.min(100,real.length/goal*100);
  return `${pageHeading('YOUR MOTION MATTERS',`${esc(state.profile.name)}님, 반가워요 <span class="hello-mark">✳</span>`,'오늘의 익숙한 움직임이, 내일의 새로운 배움이 됩니다.',`<a class="button" href="#guide">${icon('book',17)} 처음이라면, 촬영 가이드</a>`)}
    <div class="home-hero"><div class="welcome-card"><div class="welcome-copy"><span class="welcome-tag"><i></i> 오늘, 첫 움직임부터</span><h2>평범한 일상에<br>새로운 쓸모를 더해요.</h2><p>식탁을 차리고, 수건을 개는 작은 동작.<br>몸짓과 함께 나만의 기록을 시작해보세요.</p><a class="button dark" href="#missions">나에게 맞는 미션 찾기 ${icon('arrow',17)}</a></div><div class="motion-art" aria-hidden="true"><div class="motion-orbit"></div><div class="motion-cross one"></div><div class="motion-cross two"></div><div class="motion-cross three"></div><span class="art-caption">EVERYDAY → POSSIBILITY</span></div></div>
    <div class="capture-card"><div class="capture-card-top"><span class="eyebrow">READY WHEN YOU ARE</span><span>${icon('video',20)}</span></div><div class="mini-viewfinder"><span class="mini-corner"></span>${icon('camera',38)}<span>YOUR NEXT RECORDING</span></div><div class="capture-card-bottom"><div><h3>준비됐다면, 바로 촬영</h3><p>카메라 또는 저장된 영상으로 시작해요.</p></div><button class="round-capture" data-action="camera" aria-label="카메라 촬영 시작">${icon('arrow',23)}</button></div></div></div>
    <div class="stats-strip"><div><span class="stat-icon">${icon('video',20)}</span><span><small>내가 남긴 기록</small><b>${real.length}<em>개</em></b></span></div><div><span class="stat-icon">${icon('clock',20)}</span><span><small>모인 시간</small><b>${Math.floor(seconds/60)}<em>분 ${Math.floor(seconds%60)}초</em></b></span></div><div><span class="stat-icon">${icon('checkCircle',20)}</span><span><small>준비 완료</small><b>${ready}<em>개</em></b></span></div><div class="goal-stat"><span><small>내 기록 목표 <a href="#profile" aria-label="기록 목표 수정">${icon('settings',14)}</a></small><b>${real.length}<em>/ ${goal}개</em></b></span><div class="goal-ring" style="--progress:${progress}%"><span>${Math.round(progress)}<small>%</small></span></div></div></div>
    <section class="content-section"><div class="section-title"><div><h2>가볍게 시작하기 좋은 미션 <span class="count-label">${missions.length}</span></h2><p>준비물은 익숙한 물건, 그리고 두 손이면 충분해요.</p></div><a href="#missions" class="text-action">전체 미션 ${icon('arrow',16)}</a></div><div class="mission-grid">${missions.slice(0,3).map(missionCard).join('')}</div></section>
    <section class="content-section"><div class="section-title"><div><h2>최근 기록</h2><p>웹에서 시작하고, 앱에서도 이어서 확인하세요.</p></div><a href="#library" class="text-action">내 기록 전체 ${icon('arrow',16)}</a></div><div class="panel">${state.clips.length?clipRows(state.clips.slice(0,4)):empty()}</div></section><div class="bottom-note">${icon('folder',17)}<p>이 화면은 로컬 데모예요. 영상은 이 브라우저에 저장되며, 실제 제출이나 보상은 진행되지 않아요.</p><a href="../app/">앱에서 보기 ${icon('arrowUp',14)}</a></div>`;
}
function missionPage(){return `${pageHeading('FIND YOUR EVERYDAY','어떤 일상을 담아볼까요?','친숙한 동작부터 시작해보세요. 모든 미션은 체험을 위한 예시입니다.')}<div class="filter-row" aria-label="미션 분야">${['전체',...new Set(missions.map(m=>m.category))].map(category=>`<button class="filter-chip ${state.category===category?'active':''}" data-action="category" data-category="${category}" aria-pressed="${state.category===category}">${category}</button>`).join('')}<span class="filter-count">${missions.filter(m=>state.category==='전체'||m.category===state.category).length}개의 미션</span></div><div class="mission-grid all-missions">${missions.filter(m=>state.category==='전체'||m.category===state.category).map(missionCard).join('')}</div><div class="guide-banner"><span>${icon('book',26)}</span><div><h3>좋은 기록은 좋은 준비에서</h3><p>촬영 전 1분, 손과 물건이 잘 보이는지 확인해보세요.</p></div><a class="button" href="#guide">촬영 가이드 ${icon('arrow',16)}</a></div>`;}
function library(){return `${pageHeading('YOUR MOTION LIBRARY','하나씩 쌓이는 나의 기록','같은 브라우저의 웹과 앱이 하나의 기록함을 사용해요.',`<button class="button primary" data-action="upload">${icon('upload',17)} 영상 가져오기</button>`)}<div class="library-toolbar"><label class="search-field">${icon('search',18)}<input id="record-search" type="search" placeholder="기록 이름, 미션, 메모 검색" value="${esc(state.query)}" aria-label="내 기록 검색"></label><label class="sr-only" for="record-status">기록 상태</label><select id="record-status"><option value="all">모든 상태</option><option value="ready" ${state.status==='ready'?'selected':''}>준비 완료</option><option value="draft" ${state.status==='draft'?'selected':''}>초안</option></select><label class="sr-only" for="record-sort">정렬 순서</label><select id="record-sort"><option value="newest">최신순</option><option value="oldest" ${state.sort==='oldest'?'selected':''}>오래된순</option><option value="title" ${state.sort==='title'?'selected':''}>이름순</option></select></div><div class="library-summary"><span id="record-count"></span><span>저장 공간 ${formatBytes(state.clips.reduce((sum,c)=>sum+c.size,0))}</span></div><section class="panel" id="library-results" aria-label="저장한 기록"></section><div class="bottom-note">${icon('help',17)}<p>브라우저 데이터를 지우면 기록도 삭제돼요. 보관할 영상은 기록을 열어 다운로드해주세요.</p></div>`;}
function renderLibraryResults(){
  const filtered=state.clips.filter(c=>(state.status==='all'||c.status===state.status)&&`${c.title} ${c.category} ${c.notes}`.toLowerCase().includes(state.query.toLowerCase()));
  if(state.sort==='oldest')filtered.reverse();if(state.sort==='title')filtered.sort((a,b)=>a.title.localeCompare(b.title,'ko'));
  document.querySelector('#record-count').textContent=`전체 ${state.clips.length}개 · 표시 ${filtered.length}개`;
  document.querySelector('#library-results').innerHTML=!state.clips.length?empty():filtered.length?clipRows(filtered):`<div class="empty-state">${icon('search',32)}<h3>일치하는 기록이 없어요</h3><p>다른 검색어나 상태를 선택해주세요.</p><button class="button" data-action="reset-filter">검색 초기화</button></div>`;
}
function guide(){return `${pageHeading('A LITTLE GUIDE','좋은 기록을 만드는 작은 습관','복잡한 장비보다 중요한 건, 손과 물건이 잘 보이는 한 장면이에요.')}<div class="guide-grid"><div class="guide-visual"><div class="guide-viewfinder">${artwork(missions[0])}<span class="view-label">${icon('checkCircle',16)} 손과 물건을 화면 안에</span></div><p>안전하고 익숙한 일상 동작을 선택해주세요.</p></div><ol class="guide-checks"><li><span>01</span><div><h3>촬영할 공간을 준비해요</h3><p>얼굴, 주소, 신분증 등 개인정보는 화면 밖으로 치워주세요. 밝고 안정적인 곳이 좋아요.</p></div></li><li><span>02</span><div><h3>손과 물건이 잘 보이게</h3><p>카메라를 안정적으로 두고, 동작이 잘리는 부분이 없는지 미리 확인해요. 소리는 녹음하지 않아요.</p></div></li><li><span>03</span><div><h3>평소의 속도로, 자연스럽게</h3><p>뜨거운 물이나 위험한 도구 없이 할 수 있는 미션을 골라요. 촬영을 위해 무리하지 마세요.</p></div></li><li><span>04</span><div><h3>저장 전 한 번 더 확인해요</h3><p>영상을 재생하고 이름과 메모를 남겨요. 확인이 끝났다면 준비 완료로 저장하세요.</p></div></li></ol></div><section class="content-section"><div class="section-title"><h2>자주 궁금한 것들</h2></div><div class="faq-list"><details open><summary>촬영한 영상은 어디에 저장되나요?</summary><p>현재는 이 브라우저의 로컬 저장소에 저장돼요. 서버로 전송하지 않으며, 같은 주소와 브라우저로 여는 웹과 앱에서 확인할 수 있어요. 다른 기기나 브라우저에는 동기화되지 않아요.</p></details><details><summary>카메라가 켜지지 않아요.</summary><p>카메라 권한을 허용하고, 다른 앱이 카메라를 사용하는지 확인해주세요. localhost 또는 HTTPS 주소에서 촬영할 수 있어요. 카메라가 없어도 영상 가져오기를 이용할 수 있어요.</p></details><details><summary>어떤 영상 파일을 가져올 수 있나요?</summary><p>현재 브라우저에서 재생할 수 있는 250 MB 이하 영상 한 개를 가져올 수 있어요. MP4와 WebM을 권장하며, MOV 등 다른 형식은 브라우저에 따라 지원이 달라요.</p></details><details><summary>준비 완료는 검수가 끝났다는 뜻인가요?</summary><p>직접 내용을 확인하고 표시하는 로컬 상태예요. 실제 검수, 제출, 정산은 연결되어 있지 않아요.</p></details><details><summary>영상은 계속 보관되나요?</summary><p>브라우저의 데이터 삭제나 저장 공간 정리로 지워질 수 있어요. 중요한 영상은 내 기록을 열어 다운로드해주세요.</p></details></div></section>`;}
function profile(){const value=state.profileDraft||state.profile;return `${pageHeading('YOUR OWN PACE','나의 속도로, 꾸준히','웹과 앱에서 사용할 이름과 작은 목표를 정해보세요.')}<div class="profile-grid"><section class="panel profile-panel"><div class="profile-heading"><span class="large-avatar">${esc(value.name.slice(0,1))}</span><div><h2>내 프로필</h2><p>로그인 없이 사용하는 로컬 프로필</p></div></div><form id="profile-form"><label>표시 이름<input id="profile-name" maxlength="24" required value="${esc(value.name)}" autocomplete="nickname"></label><label>기록 목표<select id="profile-goal">${Array.from({length:30},(_,i)=>i+1).map(goal=>`<option value="${goal}" ${Number(value.goal)===goal?'selected':''}>${goal}개 기록하기</option>`).join('')}</select></label><button class="button primary" type="submit">프로필 저장 ${icon('check',17)}</button><p id="profile-message" class="form-message" role="status"></p></form></section><div><section class="panel profile-panel"><span class="eyebrow">ONE LIBRARY, TWO WAYS</span><h2>웹에서 앱으로, 자연스럽게</h2><p>같은 기기·브라우저·주소에서 열면 기록과 프로필이 함께 보여요. 다른 기기 간 동기화는 제공하지 않아요.</p><a class="button" href="../app/">${icon('phone',18)} 모바일 앱 열기 ${icon('arrowUp',16)}</a></section><section class="panel profile-panel sample-panel"><h3>화면을 먼저 둘러볼까요?</h3><p>영상이 없는 예시 기록 2개를 추가해 수정과 삭제를 살펴볼 수 있어요. 실제 기록 통계에서는 제외돼요.</p><button class="button" data-action="examples">예시 기록 추가</button><p class="form-message" id="example-message" role="status"></p></section></div></div>`;}
function render(){
  const focused=document.activeElement, focusId=focused?.id,selection=focused instanceof HTMLInputElement ? focused.selectionStart : null;
  state.route=location.hash.slice(1) in titles?location.hash.slice(1):'home';
  document.querySelector('#current-page').textContent=titles[state.route];document.title=`${titles[state.route]} · 몸짓 스튜디오`;
  document.querySelectorAll('[data-nav]').forEach(link=>{link.classList.toggle('active',link.dataset.nav===state.route);if(link.dataset.nav===state.route)link.setAttribute('aria-current','page');else link.removeAttribute('aria-current');});
  document.querySelector('#sidebar-name').textContent=state.profile.name;document.querySelector('#sidebar-avatar').textContent=state.profile.name.slice(0,1);document.querySelector('#top-avatar').textContent=state.profile.name.slice(0,1);
  if(state.loading){main.innerHTML='<div class="empty-state" role="status">기록을 불러오고 있어요…</div>';return;}
  main.innerHTML=(state.error?`<div class="error-box" role="alert">${esc(state.error)} <button class="button" data-action="reload">다시 불러오기</button></div>`:'')+({home,missions:missionPage,library,guide,profile}[state.route])();
  if(state.route==='library')renderLibraryResults();
  if(focusId){const next=document.getElementById(focusId);if(next&&main.contains(next)){next.focus({preventScroll:true});if(selection!==null&&next instanceof HTMLInputElement&&['text','search'].includes(next.type))next.setSelectionRange(selection,selection);}}
}
let refreshVersion=0;
async function refresh(){const version=++refreshVersion;try{const[clips,profile]=await Promise.all([getClips(),getProfile()]);if(version!==refreshVersion)return;state.clips=clips;state.profile=profile;state.error='';}catch(error){state.error=error.message||'저장소를 열지 못했어요. 일반 브라우저 창에서 다시 시도해주세요.';}state.loading=false;render();}
document.addEventListener('click',async event=>{
  const button=event.target.closest('[data-action]');if(!button)return;const action=button.dataset.action;
  if(action==='camera'||action==='upload')openCapture({mode:action==='camera'?'camera':'upload',missionId:button.dataset.id});
  if(action==='guide')openGuide(button.dataset.id);
  if(action==='clip')void openClip(button.dataset.id);
  if(action==='category'){state.category=button.dataset.category;render();document.querySelector(`[data-category="${state.category}"]`)?.focus({preventScroll:true});}
  if(action==='reset-filter'){state.query='';state.status='all';state.sort='newest';render();document.querySelector('#record-search').focus();}
  if(action==='reload')void refresh();
  if(action==='examples'){button.disabled=true;try{await addExamples();if(document.querySelector('#example-message'))document.querySelector('#example-message').textContent='예시 기록을 추가했어요. 내 기록에서 확인해주세요.';}catch(error){if(document.querySelector('#example-message'))document.querySelector('#example-message').textContent=error.message;}finally{button.disabled=false;}}
});
main.addEventListener('input',event=>{if(event.target.id==='record-search'){state.query=event.target.value;renderLibraryResults();}if(['profile-name','profile-goal'].includes(event.target.id))state.profileDraft={name:document.querySelector('#profile-name').value,goal:Number(document.querySelector('#profile-goal').value)};});
main.addEventListener('change',event=>{if(event.target.id==='record-status'){state.status=event.target.value;renderLibraryResults();}if(event.target.id==='record-sort'){state.sort=event.target.value;renderLibraryResults();}});
main.addEventListener('submit',async event=>{if(event.target.id!=='profile-form')return;event.preventDefault();const name=document.querySelector('#profile-name').value.trim();const message=document.querySelector('#profile-message');if(!name){message.textContent='표시 이름을 입력해주세요.';return;}const goal=Number(document.querySelector('#profile-goal').value),button=event.target.querySelector('button');button.disabled=true;try{await saveProfile({name,goal});state.profileDraft=null;state.profile={name,goal};render();document.querySelector('#profile-message').textContent='프로필을 저장했어요. 같은 브라우저의 앱에도 반영돼요.';}catch(error){message.textContent=error.message;}finally{button.disabled=false;}});
addEventListener('hashchange',()=>{render();window.scrollTo({top:0,behavior:'instant'});main.focus({preventScroll:true});});
subscribe(()=>void refresh());icons();void refresh();
